---
- hosts: all
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: deploy nginx docker container
      docker_container:
        image: nginx:stable
        name: nginx
        state: started
        auto_remove: true
        ports:
          - "8080:80"
